CREATE TABLE TAREFA(
    idTAREFA INT PRIMARY KEY NOT NULL,
    TITULO VARCHAR(99) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    PRAZO DATE NOT NULL,
    idDEPARTAMENTO INT NOT NULL,
    DURACAO INT NOT NULL,
    idPESSOA INT NOT NULL,
    FINALIZADO BOOLEAN
);